### ISSUE TITLE
CompileError: command 'D:\vs\VC\BIN\x86_amd64\cl.exe' failed with exit status 2

### ISSUE THREAD

**Issue by chenjun19950315** [fengkaibit/faster-rcnn_vgg16#1]
My environment:win,torch0.4.1,vs2015,cuda90

Traceback (most recent call last):
File "build.py", line 54, in 
ffi.build()
File "D:\python\lib\site-packages\torch\utils\ffi_init_.py", line 189, in build
build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
File "D:\python\lib\site-packages\torch\utils\ffi_init.py", line 111, in _build_extension
outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
File "D:\python\lib\site-packages\cffi\api.py", line 723, in compile
compiler_verbose=verbose, debug=debug, **kwds)
File "D:\python\lib\site-packages\cffi\recompiler.py", line 1526, in recompile
compiler_verbose, debug)
File "D:\python\lib\site-packages\cffi\ffiplatform.py", line 22, in compile
outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
File "D:\python\lib\site-packages\cffi\ffiplatform.py", line 58, in _build
raise VerificationError('%s: %s' % (e.class.name, e))
cffi.VerificationError: CompileError: command 'D:\vs\VC\BIN\x86_amd64\cl.exe' failed with exit status 2

Have you ever encountered this problem?

**Comment by fengkaibit** [comment]
sorry, I have not encountered this problem and I have no experience using windows to use pytorch. For this repository, my environment is ubuntu16.04, cuda9.0, pytorch0.4.1. In the later study, when I update the pytorch to 1.0.0, this ROIAlign is not work, so I used ROIAlign module in mmdetection (https://github.com/open-mmlab/mmdetection)

**Comment by chenjun19950315** [comment]
Thanks,Your answer helped me
